<?php



use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php';

if(!isset($_REQUEST['username']) || empty($_REQUEST['username'])){
	print_r(json_encode(array('status'=>0, 'message' => 'Please enter your name'))); exit;
}
//validate email
if(!isset($_REQUEST['email']) || !filter_var($_REQUEST['email'], FILTER_VALIDATE_EMAIL)){
	print_r(json_encode(array('status'=>0, 'message' => 'Please enter a valid email address'))); exit;
}

//validate subject
if(!isset($_REQUEST['subject']) || empty($_REQUEST['subject'])){
	print_r(json_encode(array('status'=> 0, 'message' => 'Please enter a subject for your message'))); exit;
}

//validate message
if(!isset($_REQUEST['message']) || empty($_REQUEST['message'])){
	print_r(json_encode(array('status'=> 0, 'message' => 'Please enter your message'))); exit;
}
if(isset($_POST['submit'])){

    $name = $_POST['username'];
    $email_address = $_POST['email'];
    $subject = $_POST['subject'];
    $message = $_POST['message'];

    $mail = new PHPMailer();


$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = 'b9dfc019271999'; //paste one generated by Mailtrap
$mail->Password = 'bf58b50005e0ec'; 
$mail->Port = 25;



$mail->setFrom('info@mailtrap.io', 'Mailtrap');
//Set an alternative reply-to address
$mail->addReplyTo('$email_address', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('daisyarusey.dc@gmail.com', 'John Doe');
$mail->addCC('daisyarusey.dc@gmail.com', 'Elena');
//Set the subject line
$mail ->isHTML(true);
$mail->Subject = 'Enquiry from Website submitted by $name';


$mail->Body = "
        <html>
            <body>
                <table style='width:600px;'>
                    <tbody>
                        <tr>
                            <td style='width:150px'><strong>Name: </strong></td>
                            <td style='width:400px'>$name</td>
                        </tr>
                        <tr>
                            <td style='width:150px'><strong>Email ID: </strong></td>
                            <td style='width:400px'>$email_address</td>
                        </tr>
                        <tr>
                            <td style='width:150px'><strong>Mobile No: </strong></td>
                            <td style='width:400px'>$subject</td>
                        </tr>
                        <tr>
                            <td style='width:150px'><strong>Message: </strong></td>
                            <td style='width:400px'>$message</td>
                        </tr>
                    </tbody>
                </table>
            </body>
        </html>
";

//send the message, check for errors
if(!$mail->Send()) {
    // Message if mail has been sent
    echo "<script>
        alert('Submission failed.');
    </script>";
}
else {
    // Message if mail has been not sent
    echo "<script>
        alert('Email has been sent successfully.');
    </script>";
}
}
?>