<?php



use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/phpmailer/phpmailer/src/Exception.php';
require 'vendor/phpmailer/phpmailer/src/PHPMailer.php';
require 'vendor/phpmailer/phpmailer/src/SMTP.php';

require 'vendor/autoload.php';

$mail = new PHPMailer(true);

$output='';


// if(!isset($_REQUEST['username']) || empty($_REQUEST['username'])){
// 	print_r(json_encode(array('status'=>0, 'message' => 'Please enter your name'))); exit;
// }
// //validate email
// if(!isset($_REQUEST['email']) || !filter_var($_REQUEST['email'], FILTER_VALIDATE_EMAIL)){
// 	print_r(json_encode(array('status'=>0, 'message' => 'Please enter a valid email address'))); exit;
// }

// //validate subject
// if(!isset($_REQUEST['subject']) || empty($_REQUEST['subject'])){
// 	print_r(json_encode(array('status'=> 0, 'message' => 'Please enter a subject for your message'))); exit;
// }

// //validate message
// if(!isset($_REQUEST['message']) || empty($_REQUEST['message'])){
// 	print_r(json_encode(array('status'=> 0, 'message' => 'Please enter your message'))); exit;
// }
if(isset($_POST['submit'])){

    $name = $_POST['username'];
    $email_address = $_POST['email'];
    $subject = $_POST['subject'];
    $message = $_POST['message'];

    

try{
$mail->isSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'alternativecircle1@gmail.com'; //paste one generated by Mailtrap
$mail->Password = 'mediocreiseasy'; 
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
$mail->Port = 587;



$mail->setFrom('alternativecircle1@gmail.com', 'Alternative Circle');
//Set an alternative reply-to address
// $mail->addReplyTo('$email_address', '$name');
//Set who the message is to be sent to
$mail->addAddress('kevin.mutiso@alternative.com', 'Kevin Mutiso');
$mail->addCC('daisyarusey.dc@gmail.com', 'Daisy Cheruto');
//Set the subject line
$mail ->isHTML(true);
$mail->Subject = "Enquiry from Website submitted by $name";


$mail->Body = "
        <html>
            <body>
                <table style='width:600px;'>
                    <tbody>
                        <tr>
                            <td style='width:150px'><strong>Name: </strong></td>
                            <td style='width:400px'>$name</td>
                        </tr>
                        <tr>
                            <td style='width:150px'><strong>Email ID: </strong></td>
                            <td style='width:400px'>$email_address</td>
                        </tr>
                        <tr>
                            <td style='width:150px'><strong>Subject: </strong></td>
                            <td style='width:400px'>$subject</td>
                        </tr>
                        <tr>
                            <td style='width:150px'><strong>Message: </strong></td>
                            <td style='width:400px'>$message</td>
                        </tr>
                    </tbody>
                </table>
            </body>
        </html>
";

//send the message, check for errors
$mail->Send();
    // Message if mail has been sent
    $output = '<div class="alert alert-success">
                  <h5>Thankyou! for contacting us, We\'ll get back to you soon!</h5>
                </div>';
}
catch(Exception $e) {
    // Message if mail has been not sent
    $output = '<div class="alert alert-danger">
                  <h5>' . $e->getMessage() . '</h5>
                </div>';
}
}
?>

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <title>Alternativecircle</title>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,900" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="css/font-awesome.css">
  <link rel="stylesheet" type="text/css" href="owl/owl.carousel.css">
  <link rel="stylesheet" type="text/css" href="owl/owl.theme.css">
  <link rel="stylesheet" type="text/css" href="css/animate.css">
  <link rel="stylesheet" type="text/css" href="style.css">
  <script type="text/javascript" src="js/jquery-2.2.0.min.js"></script>
  <script src="js/parallax.min.js"></script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAv04ynFKT8Nsp8khjkAtY4SFH0sFFZkKw&callback=initMap&libraries=&v=weekly"
    defer></script>
</head>

<body class="home">


  <nav class="navbar navbar-expand-md bg-white navbar-light fixed-top ac-nav">
    <div class="container">
      <a class="navbar-brand" href="index.html">
        <img src="images/logo.png">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a class="nav-link nav-txt" href="index.html" style="color:#000000;">Home</a></li>
          <li class="nav-item"><a class="nav-link nav-txt" href="about.html" style="color:#000000;">About Us</a></li>
          <li class="nav-item"><a class="nav-link nav-txt" href="press.html" style="color:#000000;">Press</a></li>
          <li class="nav-item"><a class="nav-link nav-txt" href="contact.php" style="color:#000000;">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="page-banner contact-top">
    <div class="container">
      <h1 class="page-heading text-center" >Contact Us</h1>
    </div>
  </div>



  <div class="triangles">
    <img src="images/triangles1.png">
  </div>

  <div class="container text-center">
    <h2 class="section-heading contact-heading">Let's get in touch</h2>
  </div>

  <div class="section contact-form">
    <div class="container">
      <div class="form-wrapper">
        <form id="frm-contact" action="#" method="post">
        <div class="form-group">
                <?= $output; ?>
        </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <input type="text" class="inputText" name="username"  required/>
                <span class="floating-label">Your name</span>
              </div>
            </div>

            <div class="col-sm-12">
              <div class="form-group">
                <input type="text" class="inputText" name="email"  required/>
                <span class="floating-label">Your email address</span>
              </div>
            </div>
            <div class="col-sm-12">
              <div class="form-group">
                <input type="text" class="inputText" name="subject" required />
                <span class="floating-label">Your subject</span>
              </div>
            </div>


            <div class="col-sm-12">
              <div class="form-group">
                <textarea class="inputText" name="message" rows="4" required></textarea>
                <span class="floating-label">Your message</span>
              </div>
            </div>

            <div class="col-sm-12">
              <div id="responses"></div>
            </div>

            <div class="col-sm-12">
              <div class="text-center">
                <a href="javascript:void(0)"><input type="submit" name="submit" value="Submit"
                  onclick="processForm()"  class="btn-send text-uppercase"></a>
                <!-- <a href="javascript:void(0)" onclick="processForm()" class="btn-send text-uppercase">Send</a> -->
              </div>
            </div>


          </div>


        </form>

        <div id="thankyou" style="display: none;">
          <div class="sent-success text-green">
            <p>Your message has been sent to our team. We will get back to you within 12 hours</p>
          </div>
        </div>


      </div>
    </div>
  </div>

  <!-- google map -->
  <div id="map">
    
  </div>


  <div class="footer">
    <div class="container text-center">
      <h4><strong>Alternative</strong>Circle</h4>
      <ul class="footer-menu">
        <li><a href="index.html">Home</a></li>
        <li><a href="about.html">About us</a></li>
        <li><a href="press.html">Press</a></li>
        <li><a href="contact.php">Contact</a></li>
      </ul>

      <p class="location">&copy; 2017 Alternative Circle | WorkStyle Africa 7th Floor, The Address, Muthangari
        Drive,&nbsp;Westlands-Nairobi</p>

      <p class="social-links">
        <a href="https://kevin-mutiso.medium.com/" target="_blank"><i class="fa fa-medium"></i></a>
        <a href="https://twitter.com/kevinmutiso?lang=en" target="_blank"><i class="fa fa-twitter"></i></a>
        <a href="https://www.linkedin.com/in/kmutiso/" target="_blank"><i class="fa fa-linkedin"></i></a>
      </p>

    </div>
  </div>




  <script type="text/javascript" src="js/bootstrap.min.js"></script>


  <script type="text/javascript">
    $(function () {
      //floating labels logic
      $('.inputText').focus(function () {
        $(this).parent().find('.floating-label').addClass('floating');
      });
  
      $('.inputText').blur(function () {
        $('.inputText').each(function () {
          if ($(this).val() == '') {
            $(this).parent().find('.floating-label').removeClass('floating');
          } else {
            $(this).parent().find('.floating-label').addClass('floating');
          }
        });
      });
    });
  
    function processForm() {
      var frm = $('#frm-contact');
      $.ajax({
        type: 'POST',
        url: frm.attr('action'),
        data: frm.serialize(),
        dataType: 'json',
        success: function (response) {
          console.log(response.status);
          if (response.status == 1) {
            //handle success
            $('#frm-contact').html($('#thankyou').html());
          } else {
            $('#responses').html(response.message);
          }
        }
      })
    }
    
  </script>
  <!-- Map location -->
  <script>
    // Initialize and add the map
    function initMap() {
      // The location of Workstyle
      const loct = { lat: -1.259831510406781, lng: 36.78110466347603 };
      // -1.259831510406781, 36.78110466347603
      // The map, centered at workstyle
      const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 18,
        center: loct,
      });
      // The marker, positioned at The Address
      const marker = new google.maps.Marker({
        position: loct,
        map: map,
      });
    }
  </script>
</body>

</html>
